vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'

        afterwork_images:
            uri_prefix: /images/afterworks
            upload_destination: '%kernel.project_dir%/public/images/afterworks'
